### ISSUE TITLE
Followed the instructions to a T, but I still get an error whenever I run the program.

### ISSUE THREAD

**Issue by bradagy** [Nick-Gottschlich/Social-Amnesia#55]
Whenever I run `python3 SocialAmnesia.py` I get the following error:

![image](https://user-images.githubusercontent.com/50127681/81238413-0babcf00-8fd0-11ea-81b3-a78a68805ef1.png)

Do you have any clue as to what  the problem could be? It was running fine a few days ago. Thanks.

**Comment by Nick-Gottschlich** [comment]
https://developer.twitter.com/en/docs/basics/response-codes Looks like that is error 89: "Invalid or expired token | The access token used in the request is incorrect or has expired."

Meaning twitter doesn't like whatever access token you entered. Maybe try making a new app on https://developer.twitter.com/en/apps and using the tokens from there?

Some good news, I'm currently working on Social Amnesia 2.0, which will allow you to log in to Twitter using oAuth, and you won't have to worry about any of the API stuff. You can check it out here if you're interested and know Javascript a bit: https://github.com/Nick-Gottschlich/Social-Amnesia/tree/master/SocialAmnesia2.0

Otherwise keep an eye out, I should have a beta soon!

**Comment by bradagy** [comment]
I appreciate it and i'll keep an eye out for v2. I didn't enter any access tokens yet. The only thing I did was install the necessary packages for the program and ran SocialAmnesia.py

**Comment by Nick-Gottschlich** [comment]
Hmm that is strange. Maybe it's some how trying to hit the API on load before any API token is set.

**Comment by a-brandon** [comment]
Same issue I'm having. Followed all the steps. Tried it on my Twitter account. It loads the tweets, but doesn't delete them.

It shows a blank page when it's supposed to show my tweets.
![image](https://user-images.githubusercontent.com/51302267/81345968-6ce2a980-9087-11ea-985f-7211f76b0f02.png)

It says the tweets have been processed, but it still doesn't work.
![image](https://user-images.githubusercontent.com/51302267/81346010-871c8780-9087-11ea-9419-3fef35aa4f65.png)

**Comment by Nick-Gottschlich** [comment]
Thanks for reporting. For now I'm gonna focus on getting Social Amnesia 2.0 beta out, as it is a huge step up from this one, I'll post in here in the coming weeks!

**Comment by Nick-Gottschlich** [comment]
Hello @a-brandon and @bradagy 

The social amnesia beta I have released here: https://github.com/Nick-Gottschlich/Social-Amnesia/releases/tag/v2.0.0-b3 should be able to take care of all of your twitter and reddit deletion needs now! The only thing I have left to implement is scheduled deletion. Please let me know, hopefully that solves your issues!

**Comment by a-brandon** [comment]
Thanks a lot for the heads up Nicholas. Will be trying it out very soon.
Thanks again for the update.

**Comment by bradagy** [comment]
I'll check it out this week. I appreciate the update 👍

**Comment by Nick-Gottschlich** [comment]
Closing this out now that Version 2 of Social Amnesia has been released.
